// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Odin.Features.MeetupPlanner.Models;

public partial class Location
{
    public Guid LocationId { get; set; }

    public string Name { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public int? MaxCapacity { get; set; }

    public bool IsActive { get; set; }
    public string Description { get; set; }

    public DateTimeOffset CreatedUtc { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset UpdatedUtc { get; set; }

    public string UpdatedBy { get; set; }

    public ICollection<Meetup> Meetups { get; set; } = new List<Meetup>();
}
