// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Odin.Features.MeetupPlanner.Models;

public partial class MeetupPlannerContext : DbContext
{
    public MeetupPlannerContext(DbContextOptions<MeetupPlannerContext> options)
        : base(options)
    {
    }

    public DbSet<Speaker> Speakers { get; set; }
    public DbSet<SpeakerBio> SpeakerBios { get; set; }
    public DbSet<Location> Locations { get; set; }
    public DbSet<Presentation> Presentations { get; set; }
    public DbSet<PresentationSpeaker> PresentationSpeakers { get; set; }
    public DbSet<Meetup> Meetups { get; set; }
    public DbSet<MeetupSpeaker> MeetupSpeakers { get; set; }
    public DbSet<ScheduleSlot> ScheduleSlots { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Speaker
        modelBuilder.Entity<Speaker>()
            .HasKey(s => s.SpeakerId);

        // SpeakerBio
        modelBuilder.Entity<SpeakerBio>()
            .HasKey(b => b.SpeakerBioId);
        modelBuilder.Entity<SpeakerBio>()
            .HasOne(b => b.Speaker)
            .WithMany(s => s.Bios)
            .HasForeignKey(b => b.SpeakerId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<SpeakerBio>()
            .HasIndex(b => new { b.SpeakerId })
            .HasFilter("[IsPrimary] = 1")
            .IsUnique();

        // Location
        modelBuilder.Entity<Location>()
            .HasKey(l => l.LocationId);

        // Presentation
        modelBuilder.Entity<Presentation>()
            .HasKey(p => p.PresentationId);

        // PresentationSpeaker (junction)
        modelBuilder.Entity<PresentationSpeaker>()
            .HasKey(ps => new { ps.PresentationId, ps.SpeakerId });
        modelBuilder.Entity<PresentationSpeaker>()
            .HasOne(ps => ps.Presentation)
            .WithMany(p => p.PresentationSpeakers)
            .HasForeignKey(ps => ps.PresentationId)
            .OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<PresentationSpeaker>()
            .HasOne(ps => ps.Speaker)
            .WithMany(s => s.PresentationSpeakers)
            .HasForeignKey(ps => ps.SpeakerId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<PresentationSpeaker>()
            .HasIndex(ps => new { ps.PresentationId })
            .HasFilter("[IsPrimary] = 1")
            .IsUnique();

        // Meetup
        modelBuilder.Entity<Meetup>()
            .HasKey(m => m.MeetupId);
        modelBuilder.Entity<Meetup>()
            .HasOne(m => m.Location)
            .WithMany(l => l.Meetups)
            .HasForeignKey(m => m.LocationId);

        // MeetupSpeaker (junction)
        modelBuilder.Entity<MeetupSpeaker>()
            .HasKey(ms => new { ms.MeetupId, ms.SpeakerId });
        modelBuilder.Entity<MeetupSpeaker>()
            .HasOne(ms => ms.Meetup)
            .WithMany(m => m.MeetupSpeakers)
            .HasForeignKey(ms => ms.MeetupId)
            .OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<MeetupSpeaker>()
            .HasOne(ms => ms.Speaker)
            .WithMany(s => s.MeetupSpeakers)
            .HasForeignKey(ms => ms.SpeakerId)
            .OnDelete(DeleteBehavior.Cascade);

        // ScheduleSlot
        modelBuilder.Entity<ScheduleSlot>()
            .HasKey(ss => ss.SlotId);
        modelBuilder.Entity<ScheduleSlot>()
            .HasOne(ss => ss.Meetup)
            .WithMany(m => m.ScheduleSlots)
            .HasForeignKey(ss => ss.MeetupId)
            .OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<ScheduleSlot>()
            .HasOne(ss => ss.Presentation)
            .WithMany(p => p.ScheduleSlots)
            .HasForeignKey(ss => ss.PresentationId)
            .OnDelete(DeleteBehavior.SetNull);

        modelBuilder.Entity<ScheduleSlot>()
            .HasIndex(ss => new { ss.MeetupId, ss.SortOrder })
            .IsUnique();
    }
}
