// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Odin.Features.MeetupPlanner.Models;

public partial class MeetupSpeaker
{
    public Guid MeetupId { get; set; }

    public Guid SpeakerId { get; set; }

    public string Role { get; set; }

    public DateTimeOffset CreatedUtc { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset UpdatedUtc { get; set; }

    public string UpdatedBy { get; set; }

    public virtual Meetup Meetup { get; set; }

    public virtual Speaker Speaker { get; set; }
}