// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Odin.Features.MeetupPlanner.Models;

public partial class Meetup
{
    public Guid MeetupId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTimeOffset StartUtc { get; set; }

    public DateTimeOffset EndUtc { get; set; }

    public Guid LocationId { get; set; }

    public string Status { get; set; }

    public int? TotalSpots { get; set; }

    public int? RsvpYesCount { get; set; }

    public int? RsvpNoCount { get; set; }

    public int? RsvpWaitlistCount { get; set; }

    public int? AttendanceCount { get; set; }

    public DateTimeOffset CreatedUtc { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset UpdatedUtc { get; set; }

    public string UpdatedBy { get; set; }

    public virtual Location Location { get; set; }

    public virtual ICollection<MeetupSpeaker> MeetupSpeakers { get; set; } = new List<MeetupSpeaker>();

    public virtual ICollection<ScheduleSlot> ScheduleSlots { get; set; } = new List<ScheduleSlot>();
}
