// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Odin.Features.MeetupPlanner.Models;

public partial class Presentation
{
    public Guid PresentationId { get; set; }
    public string Title { get; set; }
    public string Abstract { get; set; }
    public int DurationMinutes { get; set; }
    public string Status { get; set; }
    public string RepoUrl { get; set; }
    public string SlidesUrl { get; set; }
    public DateTimeOffset CreatedUtc { get; set; }
    public string CreatedBy { get; set; }
    public DateTimeOffset UpdatedUtc { get; set; }
    public string UpdatedBy { get; set; }

    public ICollection<PresentationSpeaker> PresentationSpeakers { get; set; }
    public ICollection<ScheduleSlot> ScheduleSlots { get; set; }
}
