// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Odin.Features.MeetupPlanner.Models;

public partial class ScheduleSlot
{
    public Guid SlotId { get; set; }

    public Guid MeetupId { get; set; }

    public int SortOrder { get; set; }

    public DateTimeOffset? StartUtc { get; set; }

    public DateTimeOffset? EndUtc { get; set; }

    public Guid? PresentationId { get; set; }

    public string Title { get; set; }

    public DateTimeOffset CreatedUtc { get; set; }

    public string CreatedBy { get; set; }

    public DateTimeOffset UpdatedUtc { get; set; }

    public string UpdatedBy { get; set; }

    public virtual Meetup Meetup { get; set; }

    public virtual Presentation Presentation { get; set; }
}