// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Odin.Features.MeetupPlanner.Models;

public partial class Speaker
{
    public Guid SpeakerId { get; set; }
    public string FullName { get; set; }
    public string Company { get; set; }
    public string Email { get; set; }
    public string LinkedInUrl { get; set; }
    public string TwitterUrl { get; set; }
    public string GitHubUrl { get; set; }
    public string BlogUrl { get; set; }
    public string ThumbnailUrl { get; set; }
    public DateTimeOffset CreatedUtc { get; set; }
    public string CreatedBy { get; set; }
    public DateTimeOffset UpdatedUtc { get; set; }
    public string UpdatedBy { get; set; }

    public ICollection<SpeakerBio> Bios { get; set; }
    public ICollection<PresentationSpeaker> PresentationSpeakers { get; set; }
    public ICollection<MeetupSpeaker> MeetupSpeakers { get; set; }
}
