// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Odin.Features.MeetupPlanner.Models;

public partial class SpeakerBio
{
    public Guid SpeakerBioId { get; set; }
    public Guid SpeakerId { get; set; }
    public string Title { get; set; }
    public string Bio { get; set; }
    public bool IsPrimary { get; set; }
    public DateTimeOffset CreatedUtc { get; set; }
    public string CreatedBy { get; set; }
    public DateTimeOffset UpdatedUtc { get; set; }
    public string UpdatedBy { get; set; }

    public Speaker Speaker { get; set; }
}
