<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Odin.Modules.MeetupPlanner</RootNamespace>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="9.5.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Infinity.Toolkit" Version="1.1.0" />
    <PackageReference Include="Infinity.Toolkit.AspNetCore" Version="1.0.0" />
    <PackageReference Include="Infinity.Toolkit.FeatureModules" Version="1.2.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="ModelContextProtocol" Version="0.3.0-preview.4" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="MCP\" />
  </ItemGroup>
  
</Project>
